### PR TITLE
ODA-833 preparing for changes to ChangeLog generator

### PR DESCRIPTION
**Pull request by rickreesrr**
renamed this in preparation of creating a standalone ChangeLog generator

### CODE REVIEW

**Comment by musketyr** [comment]
so do you want me to merge it or are you going to continue working on this?

**Comment by rickreesrr** [comment]
please merge it because Dexter will need it too.

**Comment by musketyr** [comment]
ok, will do as soon as the checks are finished

**Comment by rickreesrr** [comment]
Hmmm, spec failed but my one was correct. Committed fix. Frustrated with Git...

**Comment by musketyr** [comment]
you`ll get use to it soon. lgtm.

**Pull request merged**
