### PR TITLE
ODA-833 XLS Change log for RD Phenotypes and clinical tests

### PR DESCRIPTION
**Pull request by rickreesrr**
I expect to do further work on this code as part of a following related story but think it's good to get it in so  tester can have a look.
If you're interested you'll see I created a test for the method extractDeepElement() which shows where part of my issue lies - I'm sure I'll have to come back to this area.

### CODE REVIEW

**Comment by rickreesrr** [comment]
Aah, I think the 'git' issues I've been experiencing are actually some kind of slow refresh behaviour in SourceTree tool. That's why it didn't pick up the changes to the last file, even though I had changed it before committing.

**Comment by musketyr** [comment]
try to use Version Control tab or how's it called in IntelliJ, it works the best for me.

looks good to me from bird's eye view and tests are passing so I'm merging this.

**Comment by rickreesrr** [comment]
I've just done a little refactoring to enable the spec to actually test the content generated by the class - this will make me feel a lot happier! What's the easiest way to get these changes to be merged? Can I just push to the same branch or do I also need to raise another pull request? Or other?

**Comment by musketyr** [comment]
Push to same branch and open new push request.

Dne čt 28. 4. 2016 19:40 uživatel rickreesrr <notifications@github.com>
napsal:

**Pull request merged**
