### PR TITLE
Met 1006 check data model finalization

### PR DESCRIPTION
**Pull request by kuceram**
@musketyr ready to review :beer:

### CODE REVIEW

**Comment by musketyr** [comment]
@kuceram there is [failing geb spec checking the finalization broken](http://mc-travis-results.orany.cz.s3.amazonaws.com/MetadataRegistry/ModelCataloguePlugin/1541/1541.2/home/travis/reports/test-app-functional-tests-reports/test-reports/html/org/modelcatalogue/core/b/2_DataModelWizardSpec.html)

also [element service spec is broken](http://mc-travis-results.orany.cz.s3.amazonaws.com/MetadataRegistry/ModelCataloguePlugin/1541/1541.5/home/travis/reports/unit-tests-reports/test-reports/html/org/modelcatalogue/core/17_ElementServiceIntegrationSpec.html)

**Comment by kuceram** [comment]
@musketyr regarding failing integration test, isn't it a test issue? Should [here](https://github.com/MetadataRegistry/ModelCataloguePlugin/blob/2.x/ModelCatalogueCorePlugin/test/integration/org/modelcatalogue/core/ElementServiceIntegrationSpec.groovy#L82) be the code `author.versionCreated != draft.dateCreated`

**Comment by musketyr** [comment]
I'm taking care of the tests

**Comment by musketyr** [comment]
I'm merging this as we can decide later if we want any data model to be more relaxed. there is still a way how to finalize data model without the checks from the imports etc.

**Comment by kuceram** [comment]
Thanks for the tests I had to invest some time to my wife :no_good: therefore I hadn't time to fix them in time :-D

**Pull request merged**
