### PR TITLE
Met 844 export depth

### PR DESCRIPTION
**Pull request by kuceram**
@musketyr is there anyone for review :baby_bottle:

### CODE REVIEW

**Comment by musketyr** [comment]
@kuceram do you think you can take a look why the tests are failing after f4d27c80deb52b4f247d53d33b7a6d841deeed58 commit

this line may cause it: https://github.com/MetadataRegistry/ModelCataloguePlugin/commit/f4d27c80deb52b4f247d53d33b7a6d841deeed58#diff-19853a96372ef124e43d40ab54b46096L235

**Comment by musketyr** [comment]
also can you update the reports recipe to describe the new DSL concept: https://github.com/MetadataRegistry/ModelCataloguePlugin/blob/2.x/docs/development/recipes/exports.md

I would prefer

```
has depth
```

instead of

```
hasExportDepth true
```

but that's just me obsession :-)

**Comment by musketyr** [comment]
actually it looks like more parameters are coming to the exports (see MET-843) it would be great if the reports registry accepts following syntax:

```
has depth: Integer, includeMetadata: boolean
```


And than the modal will be able to render appropriate inputs for given parameters based on the expected type. but this can be done as part of different issue (e.g. MET-843).

**Comment by kuceram** [comment]
I would prefer to do it in this branch, will do so...

**Comment by kuceram** [comment]
@amilward already fixed failing test with this pull request https://github.com/MetadataRegistry/ModelCataloguePlugin/pull/530
Can we merge it to 2.x (as the tests works now) @musketyr. Than I would update (better to say rebase) remaining pull requests in order to check if they don't break something else. :-)

**Pull request merged**
