### PR TITLE
ODA-833 refactoring to enable the spec to test the content generated …

### PR DESCRIPTION
**Pull request by rickreesrr**
…by the class

### CODE REVIEW

**Comment by musketyr** [comment]
There is one failing spec: [RareDiseasePhenotypeChangeLogXlsExporterSpec](http://mc-travis-results.orany.cz.s3.amazonaws.com/MetadataRegistry/ModelCataloguePlugin/1911/1911.4/home/travis/reports/gel-integration-tests-reports/test-reports/html/org/modelcatalogue/gel/export/5_RareDiseasePhenotypeChangeLogXlsExporterSpec.html)

**Comment by rickreesrr** [comment]
Works locally so I thought it was a travis build env issue and have kicked it off again - will look harder if it fails again.

**Comment by musketyr** [comment]
ok. if it works locally, there is usually problem with ids. try to run multiple specs at once (e.g. selecting the package of the spec) and you'll see if this is the case

**Comment by rickreesrr** [comment]
Aah, what a fool I am! Yes in my joy at getting the test to pass I completely missed the hardcoded ids! Will address this afternoon.

**Pull request merged**
